# hyprl4zy shell shortcuts. Source this file only once.
bind = SUPER, P, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action power
bind = SUPER, B, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action toggleBar
bind = SUPER SHIFT, B, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action settings
bind = SUPER, H, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action help
bind = SUPER, SPACE, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action launcher
bind = SUPER, W, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action wallpaper
bind = SUPER, N, exec, ~/.config/quickshell/hyprl4zy/launcher.sh --action notifications
bind = SUPER, R, exec, ~/.config/quickshell/hyprl4zy/scripts/restart.sh
bind = SUPER SHIFT, R, exec, hyprctl reload
