general {
    gaps_in = 10
    # CSS-style gaps: top, right, bottom, left.
    gaps_out = 20,20,20,10
    border_size = 3
    col.active_border = rgba(000000ff)
    col.inactive_border = rgba(000000ff)
    resize_on_border = true
    layout = dwindle
}

# ----------------------------------------------------- 
# General window decoration
# ----------------------------------------------------- 
decoration {
    rounding = 12
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        xray = false
    }
    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(00000066)
    }
    active_opacity = 1.0
    inactive_opacity = 0.96
    fullscreen_opacity = 1.0
}
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GTK_THEME,
env = GTK_CHOSEN_THEME,

# ----------------------------------------------------- 
# Animations
# ----------------------------------------------------- 
