$background = rgb(160c12)
$foreground = rgb(a0bdbf)
$color0 = rgb(160c12)
$color1 = rgb(6A4C33)
$color2 = rgb(54394B)
$color3 = rgb(6A5351)
$color4 = rgb(96211E)
$color5 = rgb(A4532F)
$color6 = rgb(B5A84D)
$color7 = rgb(a0bdbf)
$color8 = rgb(708485)
$color9 = rgb(6A4C33)
$color10 = rgb(54394B)
$color11 = rgb(6A5351)
$color12 = rgb(96211E)
$color13 = rgb(A4532F)
$color14 = rgb(B5A84D)
$color15 = rgb(a0bdbf)

