# Minimal fallback. Customize this local file to theme your lock screen.
background {
    monitor =
    color = rgba(191619ff)
}
input-field {
    monitor =
    size = 280, 60
    position = 0, 0
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgba(f0d6adff)
    inner_color = rgba(241f25ff)
    font_color = rgba(f4eadfff)
    placeholder_text = Password
}
